### ISSUE TITLE
upload fails 

### ISSUE THREAD

**Issue by dharFr** [neocities/neocities-node#3]
Hi,

I just tried to upload my blog to my brand new neocities website (nice job btw! thx 😉 ) using [neocities-upload](https://github.com/gburnett/neocities-upload) and came up with the following error : 
``` bash
⚡ oad@oad: {master} ~/Development/blog/public
↳  neocities-upload
prompt: Username please:  oad
prompt: Password please:
undefined:1
An unhandled lowlevel error occurred. The application logs may have details.
^

SyntaxError: Unexpected token A in JSON at position 0
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/Users/oad/Development/blog/node_modules/neocities/index.js:78:25)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I did some tests with my own script an the issue seems to be related to the number of files I'm trying to upload. The upload works fine if I limit the number of files to 127, and starts failing as soon as I reach 128 (my blog is about 137 files).

**Comment by kyledrake** [comment]
Could you try this again and see if you get the same issue? I just discovered a really weird bug that was preventing empty files from being saved in certain scenarios https://github.com/neocities/neocities/commit/e52aa2929017b6e7652739ec55b9f9572e050304

I'm not sure if it would have effected this or not (haven't had a chance to test form uploads yet), but could be connected.

**Comment by dharFr** [comment]
I gave it a second try a I still get the same error. 

The script I used to highlight the behavior is available on https://github.com/dharFr/blog/blob/master/upload-cwd-to-neocities.js (uncomment [line 48](https://github.com/dharFr/blog/blob/07e97ae299461f80006027a6ccc9d4c8045e7da5/upload-cwd-to-neocities.js#L48) to limit the number of files).
